export enum ProposalSource {
  COMMERCIAL_PROPOSAL = "COMMERCIAL_PROPOSAL",
  TECHNICAL_PROPOSAL = "TECHNICAL_PROPOSAL",
  TECHNICAL_COMMERCIAL_PROPOSAL = "TECHNICAL_COMMERCIAL_PROPOSAL",
  REQUEST = "REQUEST",
  POSITION = "POSITION",
}
