export enum TechnicalCommercialProposalPositionStatus {
  NEW = 'NEW',
  REJECTED = 'REJECTED',
  SENT_TO_REVIEW = 'SENT_TO_REVIEW',
  APPROVED = 'APPROVED',
  SENT_TO_EDIT = 'SENT_TO_EDIT',
  ARCHIVE = 'ARCHIVE',
  DRAFT = 'DRAFT',
  REVIEWED = 'REVIEWED',
  PROCEDURE_IN_PROGRESS = 'PROCEDURE_IN_PROGRESS',
  PARTIALLY_REVIEWED = 'PARTIALLY_REVIEWED',
}
